In [133]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from scipy.spatial import distance

In [134]:
# numpy, pandas, matplotlib, nltk
# numpy = matrixes, math

In [135]:
# pandas = data sets 
# matplotlib = plotting
# nltk = natural language toolkit


In [136]:
df = pd.read_csv('data/ladec.csv',usecols=['id_master','c1','c2','stim','ratingcmp','ratingC1','ratingC2','correctParse'])

In [137]:
df

id_master     c1     c2        stim correctParse  ratingcmp   ratingC1  \
0          3237    gad  about    gadabout          yes  24.250000  36.541668   
1          4592  knock  about  knockabout          yes  41.461540  52.769230   
2          8231   turn  about   turnabout          yes  72.551727  82.413795   
3          6139   race  about   raceabout          yes  44.160000  73.959999   
4          8331   walk  about   walkabout          yes  68.281250  87.906250   
...         ...    ...    ...         ...          ...        ...        ...   
8951       4515   junk  yards   junkyards          yes  92.107140  91.214287   
8952       6812   ship  yards   shipyards          yes  75.285713  84.750000   
8953       2667   farm  yards   farmyards          yes  91.047623  90.380951   
8954       1007  brick  yards  brickyards          yes  81.333336  77.476189   
8955       8892    zig    zag      zigzag          yes  54.433334  48.733334   

       ratingC2  
0     44.541668  
1     38.961540  
2     54.862068  
3     40.200001  
4     56.875000  
...         ...  
8951  83.714287  
8952  67.928574  
8953  82.333336  
8954  81.476189  
8955  47.933334  

[8956 rows x 8 columns]

In [138]:
np.unique(df['correctParse']=='no',return_counts=True)

(array([False,  True]), array([8372,  584]))

In [139]:
np.unique

<function numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)>

In [140]:
df = df[df['correctParse']=='yes']

In [141]:
df

id_master     c1     c2        stim correctParse  ratingcmp   ratingC1  \
0          3237    gad  about    gadabout          yes  24.250000  36.541668   
1          4592  knock  about  knockabout          yes  41.461540  52.769230   
2          8231   turn  about   turnabout          yes  72.551727  82.413795   
3          6139   race  about   raceabout          yes  44.160000  73.959999   
4          8331   walk  about   walkabout          yes  68.281250  87.906250   
...         ...    ...    ...         ...          ...        ...        ...   
8951       4515   junk  yards   junkyards          yes  92.107140  91.214287   
8952       6812   ship  yards   shipyards          yes  75.285713  84.750000   
8953       2667   farm  yards   farmyards          yes  91.047623  90.380951   
8954       1007  brick  yards  brickyards          yes  81.333336  77.476189   
8955       8892    zig    zag      zigzag          yes  54.433334  48.733334   

       ratingC2  
0     44.541668  
1     38.961540  
2     54.862068  
3     40.200001  
4     56.875000  
...         ...  
8951  83.714287  
8952  67.928574  
8953  82.333336  
8954  81.476189  
8955  47.933334  

[8372 rows x 8 columns]

In [142]:
df.drop?

In [143]:
df.drop( labels='correctParse', axis='columns' )

id_master     c1     c2        stim  ratingcmp   ratingC1   ratingC2
0          3237    gad  about    gadabout  24.250000  36.541668  44.541668
1          4592  knock  about  knockabout  41.461540  52.769230  38.961540
2          8231   turn  about   turnabout  72.551727  82.413795  54.862068
3          6139   race  about   raceabout  44.160000  73.959999  40.200001
4          8331   walk  about   walkabout  68.281250  87.906250  56.875000
...         ...    ...    ...         ...        ...        ...        ...
8951       4515   junk  yards   junkyards  92.107140  91.214287  83.714287
8952       6812   ship  yards   shipyards  75.285713  84.750000  67.928574
8953       2667   farm  yards   farmyards  91.047623  90.380951  82.333336
8954       1007  brick  yards  brickyards  81.333336  77.476189  81.476189
8955       8892    zig    zag      zigzag  54.433334  48.733334  47.933334

[8372 rows x 7 columns]

In [144]:
embeddings_dict = {}

with open("data/glove.6B.50d.txt", 'r') as f:
    for line in f:
        values = line.split()
        word = values[0]
        vector = np.asarray(values[1:], "float32")
        embeddings_dict[word] = vector

In [145]:
c1 = np.array( df['c1'] )

c2 = np.array( df['c2'] )

cmp = np.array( df['stim'] )

In [58]:
cmp

array(['gadabout', 'knockabout', 'turnabout', ..., 'farmyards',
       'brickyards', 'zigzag'], dtype=object)

In [146]:
lexicon = pd.concat( [ pd.Series(c1), pd.Series(c2), pd.Series(cmp) ] , axis=0)

lexicon.shape, lexicon.unique().shape

((25116,), (11786,))

In [147]:
words = set(embeddings_dict.keys()).intersection(lexicon.unique())

len(words)

9302

In [45]:
#cmp_embeddings = [ embeddings_dict[x] for x in cmp if x in words ]

#How do I set this to 'None' if embedding is unavailible

In [87]:
cmp_has_embedding = np.array( [ (cmp[x] in words) for x in range( len(cmp) ) ] )

c1_has_embedding = np.array( [ (c1[x] in words) for x in range( len(c1) ) ] )

c2_has_embedding = np.array( [ (c2[x] in words) for x in range( len(c2) ) ] )

In [99]:
np.unique( c1_has_embedding, return_counts=True)

(array([False,  True]), array([   5, 8367]))

In [101]:
c1_has_embedding[-1]

#It shows 'NaN' on df_copy, I wonder why...

True

In [100]:
np.unique( c2_has_embedding, return_counts=True )

(array([False,  True]), array([  21, 8351]))

In [130]:
df_copy = pd.concat( [df,pd.Series(cmp_has_embedding) ], axis=1)

In [131]:
df_copy

id_master     c1     c2        stim correctParse  ratingcmp   ratingC1  \
0        3237.0    gad  about    gadabout          yes  24.250000  36.541668   
1        4592.0  knock  about  knockabout          yes  41.461540  52.769230   
2        8231.0   turn  about   turnabout          yes  72.551727  82.413795   
3        6139.0   race  about   raceabout          yes  44.160000  73.959999   
4        8331.0   walk  about   walkabout          yes  68.281250  87.906250   
...         ...    ...    ...         ...          ...        ...        ...   
8951     4515.0   junk  yards   junkyards          yes  92.107140  91.214287   
8952     6812.0   ship  yards   shipyards          yes  75.285713  84.750000   
8953     2667.0   farm  yards   farmyards          yes  91.047623  90.380951   
8954     1007.0  brick  yards  brickyards          yes  81.333336  77.476189   
8955     8892.0    zig    zag      zigzag          yes  54.433334  48.733334   

       ratingC2 cmp_has_embedding      0  
0     44.541668              True   True  
1     38.961540              True   True  
2     54.862068              True   True  
3     40.200001             False  False  
4     56.875000              True   True  
...         ...               ...    ...  
8951  83.714287              True    NaN  
8952  67.928574              True    NaN  
8953  82.333336              True    NaN  
8954  81.476189              True    NaN  
8955  47.933334              True    NaN  

[8946 rows x 10 columns]

In [80]:
len(cmp_has_embedding), len( df['stim'] )

(8372, 8372)

In [95]:
df_copy = df_copy.drop( labels=0, axis='columns' )

In [96]:
df_copy

id_master     c1     c2        stim correctParse  ratingcmp   ratingC1  \
0        3237.0    gad  about    gadabout          yes  24.250000  36.541668   
1        4592.0  knock  about  knockabout          yes  41.461540  52.769230   
2        8231.0   turn  about   turnabout          yes  72.551727  82.413795   
3        6139.0   race  about   raceabout          yes  44.160000  73.959999   
4        8331.0   walk  about   walkabout          yes  68.281250  87.906250   
...         ...    ...    ...         ...          ...        ...        ...   
8951     4515.0   junk  yards   junkyards          yes  92.107140  91.214287   
8952     6812.0   ship  yards   shipyards          yes  75.285713  84.750000   
8953     2667.0   farm  yards   farmyards          yes  91.047623  90.380951   
8954     1007.0  brick  yards  brickyards          yes  81.333336  77.476189   
8955     8892.0    zig    zag      zigzag          yes  54.433334  48.733334   

       ratingC2 cmp_has_embedding  
0     44.541668              True  
1     38.961540              True  
2     54.862068              True  
3     40.200001             False  
4     56.875000              True  
...         ...               ...  
8951  83.714287              True  
8952  67.928574              True  
8953  82.333336              True  
8954  81.476189              True  
8955  47.933334              True  

[8946 rows x 9 columns]

In [128]:
df.append( [df_copy,pd.Series(c1_has_embedding) ], axis='columns')

id_master     c1     c2        stim correctParse  ratingcmp   ratingC1  \
0        3237.0    gad  about    gadabout          yes  24.250000  36.541668   
1        4592.0  knock  about  knockabout          yes  41.461540  52.769230   
2        8231.0   turn  about   turnabout          yes  72.551727  82.413795   
3        6139.0   race  about   raceabout          yes  44.160000  73.959999   
4        8331.0   walk  about   walkabout          yes  68.281250  87.906250   
...         ...    ...    ...         ...          ...        ...        ...   
8951     4515.0   junk  yards   junkyards          yes  92.107140  91.214287   
8952     6812.0   ship  yards   shipyards          yes  75.285713  84.750000   
8953     2667.0   farm  yards   farmyards          yes  91.047623  90.380951   
8954     1007.0  brick  yards  brickyards          yes  81.333336  77.476189   
8955     8892.0    zig    zag      zigzag          yes  54.433334  48.733334   

       ratingC2 cmp_has_embedding      0     0  
0     44.541668              True   True  True  
1     38.961540              True   True  True  
2     54.862068              True   True  True  
3     40.200001             False  False  True  
4     56.875000              True   True  True  
...         ...               ...    ...   ...  
8951  83.714287              True    NaN   NaN  
8952  67.928574              True    NaN   NaN  
8953  82.333336              True    NaN   NaN  
8954  81.476189              True    NaN   NaN  
8955  47.933334              True    NaN   NaN  

[8946 rows x 11 columns]

In [129]:
pd.concat?

In [121]:
df_c1_array = np.array( df_copy['c1'] )

In [110]:
len(c1_has_embedding), len(df_copy['c1'])

#Why don't the lengths match?? Are there extra words in df_copy['c1']???

(8372, 8946)